baseurl = "https://realvz.github.io/blog/"
disablePathToLower = true
languageCode = "en-us"
title = "Re Alvarez Parmar's Blog"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[[menu.primary]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 2
